package com.templatedb.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import template.com.templatedb.Area;
import template.com.templatedb.Drug;
import template.com.templatedb.Institution;
import template.com.templatedb.User;

import com.templatedb.greendao.AreaDao;
import com.templatedb.greendao.DrugDao;
import com.templatedb.greendao.InstitutionDao;
import com.templatedb.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig areaDaoConfig;
    private final DaoConfig drugDaoConfig;
    private final DaoConfig institutionDaoConfig;
    private final DaoConfig userDaoConfig;

    private final AreaDao areaDao;
    private final DrugDao drugDao;
    private final InstitutionDao institutionDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        areaDaoConfig = daoConfigMap.get(AreaDao.class).clone();
        areaDaoConfig.initIdentityScope(type);

        drugDaoConfig = daoConfigMap.get(DrugDao.class).clone();
        drugDaoConfig.initIdentityScope(type);

        institutionDaoConfig = daoConfigMap.get(InstitutionDao.class).clone();
        institutionDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        areaDao = new AreaDao(areaDaoConfig, this);
        drugDao = new DrugDao(drugDaoConfig, this);
        institutionDao = new InstitutionDao(institutionDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Area.class, areaDao);
        registerDao(Drug.class, drugDao);
        registerDao(Institution.class, institutionDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        areaDaoConfig.clearIdentityScope();
        drugDaoConfig.clearIdentityScope();
        institutionDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public AreaDao getAreaDao() {
        return areaDao;
    }

    public DrugDao getDrugDao() {
        return drugDao;
    }

    public InstitutionDao getInstitutionDao() {
        return institutionDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
