package com.templatedb.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import template.com.templatedb.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "User".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "User";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property PrimaryKey = new Property(0, Long.class, "primaryKey", true, "_id");
        public final static Property Id = new Property(1, String.class, "id", false, "id");
        public final static Property Yhxm = new Property(2, String.class, "yhxm", false, "yhxm");
        public final static Property Qyysid = new Property(3, String.class, "qyysid", false, "qyysid");
        public final static Property Stamp = new Property(4, String.class, "stamp", false, "stamp");
        public final static Property Sfzh = new Property(5, String.class, "sfzh", false, "sfzh");
        public final static Property Pym = new Property(6, String.class, "pym", false, "pym");
        public final static Property Jgbh = new Property(7, String.class, "jgbh", false, "jgbh");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"User\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: primaryKey
                "\"id\" TEXT," + // 1: id
                "\"yhxm\" TEXT," + // 2: yhxm
                "\"qyysid\" TEXT," + // 3: qyysid
                "\"stamp\" TEXT," + // 4: stamp
                "\"sfzh\" TEXT," + // 5: sfzh
                "\"pym\" TEXT," + // 6: pym
                "\"jgbh\" TEXT);"); // 7: jgbh
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "UserIndex ON \"User\"" +
                " (\"id\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"User\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long primaryKey = entity.getPrimaryKey();
        if (primaryKey != null) {
            stmt.bindLong(1, primaryKey);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String yhxm = entity.getYhxm();
        if (yhxm != null) {
            stmt.bindString(3, yhxm);
        }
 
        String qyysid = entity.getQyysid();
        if (qyysid != null) {
            stmt.bindString(4, qyysid);
        }
 
        String stamp = entity.getStamp();
        if (stamp != null) {
            stmt.bindString(5, stamp);
        }
 
        String sfzh = entity.getSfzh();
        if (sfzh != null) {
            stmt.bindString(6, sfzh);
        }
 
        String pym = entity.getPym();
        if (pym != null) {
            stmt.bindString(7, pym);
        }
 
        String jgbh = entity.getJgbh();
        if (jgbh != null) {
            stmt.bindString(8, jgbh);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long primaryKey = entity.getPrimaryKey();
        if (primaryKey != null) {
            stmt.bindLong(1, primaryKey);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(2, id);
        }
 
        String yhxm = entity.getYhxm();
        if (yhxm != null) {
            stmt.bindString(3, yhxm);
        }
 
        String qyysid = entity.getQyysid();
        if (qyysid != null) {
            stmt.bindString(4, qyysid);
        }
 
        String stamp = entity.getStamp();
        if (stamp != null) {
            stmt.bindString(5, stamp);
        }
 
        String sfzh = entity.getSfzh();
        if (sfzh != null) {
            stmt.bindString(6, sfzh);
        }
 
        String pym = entity.getPym();
        if (pym != null) {
            stmt.bindString(7, pym);
        }
 
        String jgbh = entity.getJgbh();
        if (jgbh != null) {
            stmt.bindString(8, jgbh);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // primaryKey
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // yhxm
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // qyysid
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // stamp
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // sfzh
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // pym
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // jgbh
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setPrimaryKey(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setYhxm(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setQyysid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setStamp(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSfzh(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPym(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setJgbh(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setPrimaryKey(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getPrimaryKey();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getPrimaryKey() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
